name: fcmp
description: Face-controlled media player

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  youtube_player_flutter: ^8.1.1
  face_input:
    git:
      url: https://github.com/Senopiece/face_input.git
      ref: 8a7cc69e6843f3150fe2be7def2659c484258c3a # TODO: update

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
